export const seoConfig = {
  defaultTitle: "Finish your AI-built MVP before your investor pitch",
  titleTemplate: "%s | Northstar Labs",
  defaultKeywords: [
    "finish my Lovable app",
    "fix AI-generated code",
    "Cursor codebase rescue",
    "Bolt project completion",
    "v0 prototype to production",
    "MVP rescue agency",
    "investor-ready MVP",
    "non-technical founder developer",
    "Lovable to production",
    "Supabase auth fixes",
    "Stripe integration MVP",
    "AI-built MVP completion",
    "demo-ready MVP",
  ],
  markets: ["United States", "United Kingdom", "Canada", "European Union", "Australia"],
};
